name: Deploy
on:
  push:
    branches:
    - main

defaults:
  run:
    working-directory: backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version: "1.23.5"
        cache: true
        cache-dependency-path: "go.sum"
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60
    - name: generate swagger
      run: |
        go install github.com/swaggo/swag/v2/cmd/swag@v2.0.0-rc4
        go generate ./...
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
    - uses: deploys-app/deploys-action@v1
      with:
        project: PROJECT_ID
        location: LOCATION
        name: DEPLOYMENT_NAME
        image: ghcr.io/${{ github.repository }}@${{ steps.docker_build.outputs.digest }}
      env:
        DEPLOYS_AUTH_USER: ${{ secrets.DEPLOYS_AUTH_USER }}
        DEPLOYS_AUTH_PASS: ${{ secrets.DEPLOYS_AUTH_PASS }}